theme = "kanagawa"

[editor]
auto-completion = false
auto-format = true
cursorline = true
line-number = "absolute"
mouse = true
rulers = [80, 120]
scrolloff = 3
shell = ["nu", "-c"] # ["sh", "-c"], ["cmd", "/C"]
text-width = 120
true-color = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 15
max-indent-retain = 20
wrap-indicator = "…"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
character = "╎" 
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
