[[language]]
name = "c"
language-server = { command = "clangd"}

[[language]]
name = "python"
language-server = { command = "pylsp" }
#language-server = { command = "ruff-lsp" }
scope = "source.python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true


[[language]]
name = "rust"

[[language-server.rust-analyzer.config.check]]
command = "clippy"