# fg_default = "fg:#C5C9C5"
# fg_name = "fg:#C8C093"
# fg_detail "fg:#8BA4B0"
# fg_warn = "fg:#C4746E"

# bg_l1 = "bg:16161D"
# bg_l2 = "bg:1F1F28"
# bg_l3 = "bg:2A2A37"
# bg_l4 = "bg:363646"
# bg_l5 = "bg:54546D"

format = """
[](bg:#16161D fg:#16161D)\
$username\
$hostname\
[](bg:#1F1F28 fg:#16161D)\
$memory_usage\
$directory\
[](bg:#2A2A37 fg:#1F1F28)\
$git_branch\
$git_status\
$git_commit\
[](bg:#363646 fg:#2A2A37)\
$c\
$python\
$rust\
[](bg:#54546D fg:#363646)\
$time\
[ ](fg:#54546D)\n
$character
"""

[username]
show_always = true
style_user = "fg:#C8C093"
style_root = "fg:#C47463"
format = "[$user](bg:#16161D $style)"

[git_branch]
symbol = ""
style = "bg:#2A2A37 fg:#C5C9C5"
format = "[ $symbol $branch($remote_branch)]($style)"
truncation_length = 12
truncation_symbol = "…"

[git_status]
style = "bg:#2A2A37 fg:#C5C9C5"
ahead = '⇡$count'
diverged = '⇕⇡$ahead_count⇣$behind_count'
behind = '⇣$count'
format = "[($all_status$ahead_behind)]($style)"

[git_commit]
style = "bg:#2A2A37 fg:#C5C9C5"
tag_symbol = "🏷️"
format = "[$symbol]($style)[$hash]($style fg:#C8C093)[ tag=]($style)[$tag]($style fg:#8BA4B0)"


[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
style = "bg:#363646 fg:#C5C9C5"
version_format = "v${minor}"
format = "[ $symbol ]($style)[$version]($style fg:#C8C093)[ | ]($style)[$name]($style fg:#8BA4B0)"

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
style = "bg:#1F1F28 fg:#C5C9C5"
repo_root_style = "bg:1F1F28 fg:#C8C093"
read_only = " 󰌾"
read_only_style = 'bg:#F1F28 fg:#C4746E'
truncate_to_repo = true
truncation_length = 2
truncation_symbol = "…/"
format = "[ $path]($style)[$read_only]($read_only_style)"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "
style = "bg:#363646 fg:#C5C9C5"
not_capable_style = "fg:#C4746E"
version_format = "v${minor}"
format = "[ $symbol ]($style)[$version]($style fg:#C8C093)[ | ]($style)[$mod_version]($style fg:#8BA4B0)"

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
ssh_only = true
style = "bg:#16161D fg:#8BA4B0"
format = "[ $ssh_symbol $hostname]($style)"

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
threshold = 40
style = "bg:#1F1F28 fg:#C47463"
format = "[($ram/$ram_pct)]($style)"

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
style = "bg:#363646 fg:#C5C9C5"
version_format = "v${minor}"
format = "[ $symbol ]($style)[$version]($style fg:#C8C093)[ $virtualenv ]($style fg:#8BA4B0)"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
style = "bg:#363646 fg:#C5C9C5"
version_format = "v${minor}"
format = "[ $symbol ]($style)[$version]($style fg:#C8C093)[ $toolchain ]($style fg:#8BA4B0)"

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# bg_l5 fg_default
style = "bg:#54546D fg:#C5C9C5"
format = '[ $time ]($style)'

[character]
success_symbol = "[❯](fg:#938AA9)"
error_symbol = "[❯](fg:#E46876)"
vimcmd_symbol = "[❮](fg:#87a987)"
