theme = "kanagawa"

[editor]
true-color = true
shell = ["nu", "-c"]
text-width = 120
scrolloff = 3
line-number = "absolute"
cursorline = true
rulers = [80, 120]
mouse = true
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 15
max-indent-retain = 20
wrap-indicator = "…"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "╎" 
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
