[tool.black]
line-length = 120
target-version = ["py313"]
include = '\.pyi?$'
extend-exclude = '''
/(
  tests/
  | profiling/
  | build/
  | venv/
  | __pycache__
  | __pycache__/
)
'''

[tool.ruff]
line-length = 120
exclude = [
  "build/",
  "dist/"
  "migrations/",
  "profiling/",
  "tests/",
  "venv/",
  "venv-dev/"
  "__pycache__/"
]
select = ["E", "F", "C", "N", "Q"]

[tool.pylyzer]
analysis = [
  { type = "pep8", enabled = true },
  { type = "docstrings", enabled = false},
  { type = "unused_imports", enabled = true }
]
exclusions = [
  "build",
  "migrations/",
  "profiling",
  "tests/",
  "venv",
  "__pycache__/"
]

[tool.mypy]
python_version = 3.13
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true
ignore_missing_imports = true
exclude = "^(buld|dist|venv|__pycache__|tests)./*$"
