[helpers]

[default]
depends = []

[default.files]
LICENSE = ""
"README.md" = ""
config = ""

[default.variables]

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"helix/languages.toml" = "~/.config/helix/languages.toml"

[nushell.files]
"nushell/config.nu" = "~/.config/nushell/config.nu"
"nushell/env.nu" = "~/.config/nushell/.config/env.nu"

[startship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
